[compile]
target = "aarch64-unknown-none"
package = "helloworld"
log_level = "Debug"
rust_flags = "-C link-arg=-TLink.x -C link-arg=-no-pie -C link-arg=-znostart-stop-gc"
features = []

[compile.env]

[qemu]
machine = "virt"
cpu = "cortex-a53"
graphic = false
args = ""

[uboot]
serial = "COM3"
baud_rate = 115200
net = "以太网"
dtb_file = "C:/Users/zrufo/Documents/rspi/bcm2711-rpi-4-b.dtb"
