[workspace]
resolver = "2"
members = ["app/*", "crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
sparreal-rt = { path = "crates/sparreal-rt" }
sparreal-macros = { path = "crates/sparreal-macros" }
page-table-arm = { path = "crates/page-table-arm" }
driver-interface = { path = "crates/driver-interface" }
log = "0.4"
