[package]
edition.workspace = true
name = "helloworld"
publish = false
version = "0.1.0"

[dependencies]
log = {workspace = true}
sparreal-kernel = {workspace = true}
sparreal-rt = {workspace = true, features = [
  "early-print",
]}
