[package]
name = "simple_test"
version.workspace = true
edition.workspace = true

[dev-dependencies]
bare-test = { workspace = true }
log = { workspace = true }


[test-qemu.aarch64]
machine = "virt"
cpu = "cortex-a53"
graphic = false
args = ""


