[package]
name = "driver-interface"
version.workspace = true
edition.workspace = true

[dependencies]
futures = { version = "0.3", default-features = false, features = ["alloc"] }
embedded-io = "0.6"
