[package]
name = "driver-interface"
version.workspace = true
edition.workspace = true

[dependencies]
futures = { workspace = true, default-features = false, features = ["alloc"] }
embedded-io = { workspace = true }
