[package]
name = "sparreal-rt"
version = { workspace = true }
edition = { workspace = true }

[features]
default = ["early-print"]
early-print = []

[dependencies]
log = { workspace = true }
sparreal-kernel = { workspace = true, features = ["mmu"] }
page-table = { workspace = true }
page-table-generic = { workspace = true }
driver-interface = { workspace = true }
futures = { workspace = true, default-features = false, features = ["alloc"] }
embedded-io = { workspace = true }
memory_addr = { workspace = true }
sparreal-macros = { workspace = true }
bitflags = "2.6.0"

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "10.0"
tock-registers = { workspace = true }
arm-pl011-rs = { workspace = true }
flat_device_tree = { workspace = true }
arm-gic-driver = { workspace = true }
arm_pl031 = "0.2.1"

[build-dependencies]
sparreal-build = { workspace = true }
