[package]
name = "sparreal-rt"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
sparreal-kernel = { workspace = true, features = ["mmu"] }
page-table = { workspace = true }
page-table-interface = { workspace = true }
driver-interface = { workspace = true }
futures = { workspace = true, default-features = false, features = ["alloc"] }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "9.4.0"
tock-registers = { workspace = true }


[build-dependencies]
sparreal-build = { workspace = true }
