[package]
name = "sparreal-rt"
version = "0.2.0"
authors = ["Zhourui <zrufo747@outlook.com>"]
edition = "2021"
repository = "https://github.com/qclic/sparreal-os"
license = "MPL-2.0"
description = "Sparreal OS Runtime"
keywords = ["os"]
categories = ["embedded", "no-std"]

[features]
default = []
early-print = []

[dependencies]
log = "0.4"
sparreal-kernel = { version = "0.1", path = "../sparreal-kernel", features = [
    "mmu",
] }
page-table-generic = { version = "0.2.2" }
driver-interface = { version = "0.0.1", path = "../driver-interface" }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
embedded-io = "0.6"
memory_addr = "0.3"
sparreal-macros = { version = "0.0.5", path = "../sparreal-macros" }
bitflags = "2.6"
fdt-parser = "0.4"
dma-api = "0.2"


[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "10.0"
tock-registers = "0.9"
arm-pl011-rs = "0.2"
arm-gic-driver = "0.3"
# arm_pl031 = "0.2.1"
page-table-arm = { version = "0.1", path = "../page-table-arm" }
