[package]
name = "sparreal-kernel"
version = { workspace = true }
edition = { workspace = true }

[features]
mmu = []


[dependencies]
log = "0.4"
buddy_system_allocator = "0.10"
sparreal-macros = { version = "0.0.1", path = "../sparreal-macros" }
memory_addr = "0.3"
page-table-generic = { version = "0.0.1", path = "../page-table-generic" }
fdt-parser = "0.3.5"
lock_api = { workspace = true }
driver-interface = { workspace = true }
pasts = { version = "0.14", default-features = false }
rgb = { workspace = true }
ansi_rgb = { workspace = true }
embedded-hal-async = "1.0"
spin_on = "0.1"
