[package]
name = "sparreal-kernel"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
buddy_system_allocator = "0.10"
sparreal-macros = { workspace = true }
page_table = { workspace = true }


[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "9.4.0"
tock-registers = { workspace = true }