[package]
name = "sparreal-kernel"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
buddy_system_allocator = "0.10"
sparreal-macros = { workspace = true }
memory_addr = { workspace = true }
page-table-interface = { workspace = true }
flat_device_tree = { workspace = true }
