[package]
name = "bare-test"
version.workspace = true
edition.workspace = true

[dependencies]
sparreal-rt = { path = "../sparreal-rt", no-default-features = true }
log = { workspace = true, features = ["max_level_error"] }
