name: Check, Build and Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # ZR233/ostool requires
    - name: Install qemu-system
      run: sudo apt update && sudo apt install qemu-system -y 
    - name: Install libudev-dev
      run: sudo apt update && sudo apt install libudev-dev -y
    - name: Install cargo-binutils
      run: cargo install cargo-binutils
    - name: Install ostool
      run: cargo install ostool

    - name: Install toolchain
      run: rustup show
    - name: Check rust version
      run: rustc --version --verbose
    - name: Check code format
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Clippy for each package
      run: cargo metadata --format-version 1 --no-deps | jq -r ".packages | .[] | .name" | awk '{cmd="cargo clippy -p " $0 " -- -D warnings"; print cmd; status = system(cmd); if (status != 0) {exit 1;} }'

    # - name: Build
    #   run: cargo build 

    - name: Build sparreal-kernel with mmu features
      working-directory: crates/sparreal-kernel
      run: cargo build -F mmu

    - name: Clippy sparreal-kernel with mmu features
      working-directory: crates/sparreal-kernel
      run: cargo clippy -F mmu -- -D warnings

    - name: Build sparreal-rt with early-print features
      working-directory: crates/sparreal-rt
      run: cargo build -F early-print

    - name: Clippy sparreal-rt with early-print features
      working-directory: crates/sparreal-rt
      run: cargo clippy -F early-print -- -D warnings

    - name: Test bare-test simple_test
      working-directory: app/simple_test
      run: cargo test --test test1

    - name: Test sparreal-macros
      working-directory: crates/sparreal-macros
      run: cargo test

    - name: Test sparreal-kernel
      working-directory: crates/sparreal-kernel
      run: cargo test

    - name: Test page-table-arm
      working-directory: crates/page-table-arm
      run: cargo test
