name: Check, Build and Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # ZR233/ostool requires
    - name: Install qemu-system
      run: sudo apt update && sudo apt install qemu-system -y 
    - name: Install libudev-dev
      run: sudo apt update && sudo apt install libudev-dev -y
    - name: Install cargo-binutils
      run: cargo install cargo-binutils
    - name: Install ostool
      run: cargo install ostool

    - name: Install toolchain
      run: rustup show
    - name: Check rust version
      run: rustc --version --verbose
    - name: Check code format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy -- -D warnings
    # - name: Build
    #   run: cargo build 

    - name: Test bare-test simple_test
      working-directory: app/simple_test
      run: cargo test --test test1

    - name: Test sparreal-macros
      working-directory: crates/sparreal-macros
      run: cargo test

    - name: Test sparreal-kernel
      working-directory: crates/sparreal-kernel
      run: cargo test

    - name: Test page-table-arm
      working-directory: crates/page-table-arm
      run: cargo test
